
version: 2

models:
  - name: acceptance_report
    description: Transformed model for the Acceptance report.
    columns:
      - name: external_ref
        description: Reference ID for the transaction.
        tests:
          - not_null
          - unique
      - name: status
        description: Status of the transaction.
        tests:
          - not_null
      - name: source
        description: Source of the transaction.
        tests:
          - not_null
      - name: ref
        description: Reference information for the transaction.
        tests:
          - not_null
      - name: date_time
        description: Date and time of the transaction.
        tests:
          - not_null
      - name: state
        description: State of the transaction.
      - name: cvv_provided
        description: Indicates whether CVV was provided.
      - name: amount
        description: Amount of the transaction.
        tests:
          - not_null
      - name: country
        description: Country of the transaction.
        tests:
          - not_null
      - name: currency
        description: Currency of the transaction.
        tests:
          - not_null
      - name: rates
        description: Rates associated with the transaction.
      - name: amount_usd
        description: Amount of the transaction in USD.
        tests:
          - not_null
      - name: chargeback
        description: Chargeback information for the transaction.